# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/qcom/common/extractors/setup-makefiles.sh


ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/qcom/binaries/bluetooth/proprietary/vendor/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so:system/vendor/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so \
    vendor/qcom/binaries/bluetooth/proprietary/vendor/lib/libaptXHD-1.0.0-rel-Android21-ARMv7A.so:system/vendor/lib/libaptXHD-1.0.0-rel-Android21-ARMv7A.so \
    vendor/qcom/binaries/bluetooth/proprietary/vendor/lib/libaptXScheduler.so:system/vendor/lib/libaptXScheduler.so

PRODUCT_PROPERTY_OVERRIDES += \
    persist.bt.enableAptXHD=true
endif
